// This code was generated by an EVALUATION copy of Schematrix SchemaCoder.
// Redistribution of this source code, or an application developed from it, is forbidden.
// Modification of this source code to remove this comment is also forbidden.
// Please visit http://www.schematrix.com/ to obtain a license to use this software.

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.IO;

namespace JTMSProject
{
    public partial class ClientgroupMaster
    {
        private static IClientgroupMasterPersister _DefaultPersister;
        private IClientgroupMasterPersister _Persister;
        private int _CTGId;
        private int? _CompId;
        private int? _id;
        private string _ClientGroupName;

        static ClientgroupMaster()
        {
            // Assign default persister
            _DefaultPersister = new SqlServerClientgroupMasterPersister();
        }

        public ClientgroupMaster()
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister; 
        }

        public ClientgroupMaster(int _CTGId)
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister; 

            // Assign method parameter to private fields
            this._CTGId = _CTGId; 

            // Call associated retrieve method
            Retrieve();
        }

        public ClientgroupMaster(DataRow row)
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister; 

            // Assign column values to private members
            for (int  i = 0; i < row.Table.Columns.Count; i++)
            {
                switch (row.Table.Columns[i].ColumnName.ToUpper())
                {
                    case "CTGID":
                        this.CTGId = Convert.ToInt32(row[i, DataRowVersion.Current]); 
                        break;
                    
                    case "COMPID":
                        if(row.IsNull(i) == false)
                        {
                            this.CompId = Convert.ToInt32(row[i, DataRowVersion.Current]); 
                        }
                        break;
                    
                    case "ID":
                        if(row.IsNull(i) == false)
                        {
                            this.id = Convert.ToInt32(row[i, DataRowVersion.Current]); 
                        }
                        break;
                    
                    case "CLIENTGROUPNAME":
                        if(row.IsNull(i) == false)
                        {
                            this.ClientGroupName = (string)row[i, DataRowVersion.Current]; 
                        }
                        break;
                    
                }
            }
        }

        public static IClientgroupMasterPersister DefaultPersister
        {
            get { return _DefaultPersister; }
            set { _DefaultPersister = value; }
        }

        public IClientgroupMasterPersister Persister
        {
            get { return _Persister; }
            set { _Persister = value; }
        }

        public int CTGId
        {
            get { return _CTGId; }
            set { _CTGId = value; }
        }

        public int? CompId
        {
            get { return _CompId; }
            set { _CompId = value; }
        }

        public int? id
        {
            get { return _id; }
            set { _id = value; }
        }

        public string ClientGroupName
        {
            get { return _ClientGroupName; }
            set { _ClientGroupName = value; }
        }

        public virtual void Clone(ClientgroupMaster sourceObject)
        {
            // Clone attributes from source object
            this._CTGId = sourceObject.CTGId; 
            this._CompId = sourceObject.CompId; 
            this._id = sourceObject.id; 
            this._ClientGroupName = sourceObject.ClientGroupName; 
        }

        public virtual int Retrieve()
        {
            return _Persister.Retrieve(this); 
        }

        public virtual int Update()
        {
            return _Persister.Update(this); 
        }

        public virtual int Delete()
        {
            return _Persister.Delete(this); 
        }

        public virtual int Insert()
        {
            return _Persister.Insert(this); 
        }

        public static IReader<ClientgroupMaster> ListAll()
        {
            return _DefaultPersister.ListAll(); 
        }

    }
    
    public partial interface IClientgroupMasterPersister
    {
        int Retrieve(ClientgroupMaster clientgroupMaster);
        int Update(ClientgroupMaster clientgroupMaster);
        int Delete(ClientgroupMaster clientgroupMaster);
        int Insert(ClientgroupMaster clientgroupMaster);
        IReader<ClientgroupMaster> ListAll();
    }
    
    public partial class SqlServerClientgroupMasterPersister : SqlPersisterBase, IClientgroupMasterPersister
    {
        public SqlServerClientgroupMasterPersister()
        {
        }

        public SqlServerClientgroupMasterPersister(string connectionString) : base(connectionString)
        {
        }

        public SqlServerClientgroupMasterPersister(SqlConnection connection) : base(connection)
        {
        }

        public SqlServerClientgroupMasterPersister(SqlTransaction transaction) : base(transaction)
        {
        }

        public int Retrieve(ClientgroupMaster clientgroupMaster)
        {
            int __rowsAffected = 1;
            
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("ClientgroupMasterGet"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Add command parameters
                    SqlParameter vCTGId = new SqlParameter("@CTGId", SqlDbType.Int);
                    vCTGId.Direction = ParameterDirection.InputOutput; 
                    sqlCommand.Parameters.Add(vCTGId);
                    SqlParameter vCompId = new SqlParameter("@CompId", SqlDbType.Int);
                    vCompId.Direction = ParameterDirection.Output; 
                    sqlCommand.Parameters.Add(vCompId);
                    SqlParameter vid = new SqlParameter("@id", SqlDbType.Int);
                    vid.Direction = ParameterDirection.Output; 
                    sqlCommand.Parameters.Add(vid);
                    SqlParameter vClientGroupName = new SqlParameter("@ClientGroupName", SqlDbType.VarChar, 70);
                    vClientGroupName.Direction = ParameterDirection.Output; 
                    sqlCommand.Parameters.Add(vClientGroupName);

                    // Set input parameter values
                    SqlServerHelper.SetParameterValue(vCTGId, clientgroupMaster.CTGId);

                    // Execute command
                    sqlCommand.ExecuteNonQuery();

                    try
                    {
                        // Get output parameter values
                        clientgroupMaster.CTGId = SqlServerHelper.ToInt32(vCTGId); 
                        clientgroupMaster.CompId = SqlServerHelper.ToNullableInt32(vCompId); 
                        clientgroupMaster.id = SqlServerHelper.ToNullableInt32(vid); 
                        clientgroupMaster.ClientGroupName = SqlServerHelper.ToString(vClientGroupName); 

                    }
                    catch(Exception ex)
                    {
                        if(ex is System.NullReferenceException)
                        {
                            __rowsAffected = 0; 
                        }
                        else
                        {
                            throw ex; 
                        }
                    }
                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }
            
            return __rowsAffected; 
        }

        public int Update(ClientgroupMaster clientgroupMaster)
        {
            int __rowsAffected = 0;
            
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("ClientgroupMasterUpdate"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                // Add command parameters
                SqlParameter vCTGId = new SqlParameter("@CTGId", SqlDbType.Int);
                vCTGId.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vCTGId);
                SqlParameter vCompId = new SqlParameter("@CompId", SqlDbType.Int);
                vCompId.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vCompId);
                SqlParameter vid = new SqlParameter("@id", SqlDbType.Int);
                vid.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vid);
                SqlParameter vClientGroupName = new SqlParameter("@ClientGroupName", SqlDbType.VarChar, 70);
                vClientGroupName.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vClientGroupName);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(vCTGId, clientgroupMaster.CTGId);
                SqlServerHelper.SetParameterValue(vCompId, clientgroupMaster.CompId);
                SqlServerHelper.SetParameterValue(vid, clientgroupMaster.id);
                SqlServerHelper.SetParameterValue(vClientGroupName, clientgroupMaster.ClientGroupName);

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery(); 
                    if(__rowsAffected == 0)
                    {
                        return __rowsAffected; 
                    }
                    

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }
            
            return __rowsAffected; 
        }

        public int Delete(ClientgroupMaster clientgroupMaster)
        {
            int __rowsAffected = 0;
            
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("ClientgroupMasterDelete"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Add command parameters
                    SqlParameter vCTGId = new SqlParameter("@CTGId", SqlDbType.Int);
                    vCTGId.Direction = ParameterDirection.Input; 
                    sqlCommand.Parameters.Add(vCTGId);

                    // Set input parameter values
                    SqlServerHelper.SetParameterValue(vCTGId, clientgroupMaster.CTGId);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery(); 

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }
            
            return __rowsAffected; 
        }

        public int Insert(ClientgroupMaster clientgroupMaster)
        {
            int __rowsAffected = 0;
            
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("ClientgroupMasterInsert"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                // Add command parameters
                SqlParameter vCTGId = new SqlParameter("@CTGId", SqlDbType.Int);
                vCTGId.Direction = ParameterDirection.InputOutput; 
                sqlCommand.Parameters.Add(vCTGId);
                SqlParameter vCompId = new SqlParameter("@CompId", SqlDbType.Int);
                vCompId.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vCompId);
                SqlParameter vid = new SqlParameter("@id", SqlDbType.Int);
                vid.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vid);
                SqlParameter vClientGroupName = new SqlParameter("@ClientGroupName", SqlDbType.VarChar, 70);
                vClientGroupName.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vClientGroupName);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(
                    vCTGId, 
                    clientgroupMaster.CTGId, 
                    0);
                SqlServerHelper.SetParameterValue(vCompId, clientgroupMaster.CompId);
                SqlServerHelper.SetParameterValue(vid, clientgroupMaster.id);
                SqlServerHelper.SetParameterValue(vClientGroupName, clientgroupMaster.ClientGroupName);

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery(); 
                    if(__rowsAffected == 0)
                    {
                        return __rowsAffected; 
                    }
                    

                    // Get output parameter values
                    clientgroupMaster.CTGId = SqlServerHelper.ToInt32(vCTGId); 

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }
            
            return __rowsAffected; 
        }

        public IReader<ClientgroupMaster> ListAll()
        {
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("ClientgroupMasterListAll"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                // Execute command
                SqlDataReader reader = sqlCommand.ExecuteReader(AttachReaderCommand(sqlCommand));

                // Return reader
                return new SqlServerClientgroupMasterReader(reader); 
            }
        }

    }

    public partial class SqlServerClientgroupMasterReader : IReader<ClientgroupMaster>
    {
        private SqlDataReader sqlDataReader;

        private ClientgroupMaster _ClientgroupMaster;

        private int _CTGIdOrdinal = -1;
        private int _CompIdOrdinal = -1;
        private int _idOrdinal = -1;
        private int _ClientGroupNameOrdinal = -1;

        public SqlServerClientgroupMasterReader(SqlDataReader sqlDataReader)
        {
            this.sqlDataReader = sqlDataReader; 
            for (int  i = 0; i < sqlDataReader.FieldCount; i++)
            {
                string columnName = sqlDataReader.GetName(i);
                columnName = columnName.ToUpper(); 
                switch (columnName)
                {
                    case "CTGID":
                        _CTGIdOrdinal = i; 
                        break;
                    
                    case "COMPID":
                        _CompIdOrdinal = i; 
                        break;
                    
                    case "ID":
                        _idOrdinal = i; 
                        break;
                    
                    case "CLIENTGROUPNAME":
                        _ClientGroupNameOrdinal = i; 
                        break;
                    
                }
            }
        }

        #region IReader<ClientgroupMaster> Implementation
        
        public bool Read()
        {
            _ClientgroupMaster = null; 
            return this.sqlDataReader.Read(); 
        }

        public ClientgroupMaster Current
        {
            get
            {
                if(_ClientgroupMaster == null)
                {
                    _ClientgroupMaster = new ClientgroupMaster();
                    if(_CTGIdOrdinal != -1)
                    {
                        _ClientgroupMaster.CTGId = SqlServerHelper.ToInt32(sqlDataReader, _CTGIdOrdinal); 
                    }
                    _ClientgroupMaster.CompId = SqlServerHelper.ToNullableInt32(sqlDataReader, _CompIdOrdinal); 
                    _ClientgroupMaster.id = SqlServerHelper.ToNullableInt32(sqlDataReader, _idOrdinal); 
                    _ClientgroupMaster.ClientGroupName = SqlServerHelper.ToString(sqlDataReader, _ClientGroupNameOrdinal); 
                }
                

                return _ClientgroupMaster; 
            }
        }

        public void Close()
        {
            sqlDataReader.Close();
        }

        public List<ClientgroupMaster> ToList()
        {
            List<ClientgroupMaster> list = new List<ClientgroupMaster>();
            while(this.Read())
            {
                list.Add(this.Current);
            }
            this.Close();
            return list; 
        }

        public DataTable ToDataTable()
        {
            DataTable dataTable = new DataTable();
            dataTable.Load(sqlDataReader);
            return dataTable; 
        }

        #endregion
        
        #region IDisposable Implementation
        
        public void Dispose()
        {
            sqlDataReader.Dispose();
        }
        #endregion
        
        #region IEnumerable<ClientgroupMaster> Implementation
        
        public IEnumerator<ClientgroupMaster> GetEnumerator()
        {
            return new ClientgroupMasterEnumerator(this); 
        }

        #endregion
        
        #region IEnumerable Implementation
        
        IEnumerator IEnumerable.GetEnumerator()
        {
            return new ClientgroupMasterEnumerator(this); 
        }

        #endregion
        
        
        private partial class ClientgroupMasterEnumerator : IEnumerator<ClientgroupMaster>
        {
            private IReader<ClientgroupMaster> clientgroupMasterReader;

            public ClientgroupMasterEnumerator(IReader<ClientgroupMaster> clientgroupMasterReader)
            {
                this.clientgroupMasterReader = clientgroupMasterReader; 
            }

            #region IEnumerator<ClientgroupMaster> Members
            
            public ClientgroupMaster Current
            {
                get { return this.clientgroupMasterReader.Current; }
            }

            #endregion
            
            #region IDisposable Members
            
            public void Dispose()
            {
                this.clientgroupMasterReader.Dispose();
            }

            #endregion
            
            #region IEnumerator Members
            
            object IEnumerator.Current
            {
                get { return this.clientgroupMasterReader.Current; }
            }

            public bool MoveNext()
            {
                return this.clientgroupMasterReader.Read(); 
            }

            public void Reset()
            {
                throw new Exception("Reset of clientgroupmaster reader is not supported."); 
            }

            #endregion
            
        }
    }
}
