// This code was generated by an EVALUATION copy of Schematrix SchemaCoder.
// Redistribution of this source code, or an application developed from it, is forbidden.
// Modification of this source code to remove this comment is also forbidden.
// Please visit http://www.schematrix.com/ to obtain a license to use this software.

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.IO;

namespace JTMSProject
{
    public partial class DepartmentMaster
    {
        private static IDepartmentMasterPersister _DefaultPersister;
        private IDepartmentMasterPersister _Persister;
        private int _DepId;
        private int? _CompId;
        private int? _id;
        private string _DepartmentName;

        static DepartmentMaster()
        {
            // Assign default persister
            _DefaultPersister = new SqlServerDepartmentMasterPersister();
        }

        public DepartmentMaster()
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister; 
        }

        public DepartmentMaster(int _DepId)
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister; 

            // Assign method parameter to private fields
            this._DepId = _DepId; 

            // Call associated retrieve method
            Retrieve();
        }

        public DepartmentMaster(DataRow row)
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister; 

            // Assign column values to private members
            for (int  i = 0; i < row.Table.Columns.Count; i++)
            {
                switch (row.Table.Columns[i].ColumnName.ToUpper())
                {
                    case "DEPID":
                        this.DepId = Convert.ToInt32(row[i, DataRowVersion.Current]); 
                        break;
                    
                    case "COMPID":
                        if(row.IsNull(i) == false)
                        {
                            this.CompId = Convert.ToInt32(row[i, DataRowVersion.Current]); 
                        }
                        break;
                    
                    case "ID":
                        if(row.IsNull(i) == false)
                        {
                            this.id = Convert.ToInt32(row[i, DataRowVersion.Current]); 
                        }
                        break;
                    
                    case "DEPARTMENTNAME":
                        if(row.IsNull(i) == false)
                        {
                            this.DepartmentName = (string)row[i, DataRowVersion.Current]; 
                        }
                        break;
                    
                }
            }
        }

        public static IDepartmentMasterPersister DefaultPersister
        {
            get { return _DefaultPersister; }
            set { _DefaultPersister = value; }
        }

        public IDepartmentMasterPersister Persister
        {
            get { return _Persister; }
            set { _Persister = value; }
        }

        public int DepId
        {
            get { return _DepId; }
            set { _DepId = value; }
        }

        public int? CompId
        {
            get { return _CompId; }
            set { _CompId = value; }
        }

        public int? id
        {
            get { return _id; }
            set { _id = value; }
        }

        public string DepartmentName
        {
            get { return _DepartmentName; }
            set { _DepartmentName = value; }
        }

        public virtual void Clone(DepartmentMaster sourceObject)
        {
            // Clone attributes from source object
            this._DepId = sourceObject.DepId; 
            this._CompId = sourceObject.CompId; 
            this._id = sourceObject.id; 
            this._DepartmentName = sourceObject.DepartmentName; 
        }

        public virtual int Retrieve()
        {
            return _Persister.Retrieve(this); 
        }

        public virtual int Update()
        {
            return _Persister.Update(this); 
        }

        public virtual int Delete()
        {
            return _Persister.Delete(this); 
        }

        public virtual int Insert()
        {
            return _Persister.Insert(this); 
        }

        public static IReader<DepartmentMaster> ListAll()
        {
            return _DefaultPersister.ListAll(); 
        }

    }
    
    public partial interface IDepartmentMasterPersister
    {
        int Retrieve(DepartmentMaster departmentMaster);
        int Update(DepartmentMaster departmentMaster);
        int Delete(DepartmentMaster departmentMaster);
        int Insert(DepartmentMaster departmentMaster);
        IReader<DepartmentMaster> ListAll();
    }
    
    public partial class SqlServerDepartmentMasterPersister : SqlPersisterBase, IDepartmentMasterPersister
    {
        public SqlServerDepartmentMasterPersister()
        {
        }

        public SqlServerDepartmentMasterPersister(string connectionString) : base(connectionString)
        {
        }

        public SqlServerDepartmentMasterPersister(SqlConnection connection) : base(connection)
        {
        }

        public SqlServerDepartmentMasterPersister(SqlTransaction transaction) : base(transaction)
        {
        }

        public int Retrieve(DepartmentMaster departmentMaster)
        {
            int __rowsAffected = 1;
            
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("DepartmentMasterGet"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Add command parameters
                    SqlParameter vDepId = new SqlParameter("@DepId", SqlDbType.Int);
                    vDepId.Direction = ParameterDirection.InputOutput; 
                    sqlCommand.Parameters.Add(vDepId);
                    SqlParameter vCompId = new SqlParameter("@CompId", SqlDbType.Int);
                    vCompId.Direction = ParameterDirection.Output; 
                    sqlCommand.Parameters.Add(vCompId);
                    SqlParameter vid = new SqlParameter("@id", SqlDbType.Int);
                    vid.Direction = ParameterDirection.Output; 
                    sqlCommand.Parameters.Add(vid);
                    SqlParameter vDepartmentName = new SqlParameter("@DepartmentName", SqlDbType.VarChar, 70);
                    vDepartmentName.Direction = ParameterDirection.Output; 
                    sqlCommand.Parameters.Add(vDepartmentName);

                    // Set input parameter values
                    SqlServerHelper.SetParameterValue(vDepId, departmentMaster.DepId);

                    // Execute command
                    sqlCommand.ExecuteNonQuery();

                    try
                    {
                        // Get output parameter values
                        departmentMaster.DepId = SqlServerHelper.ToInt32(vDepId); 
                        departmentMaster.CompId = SqlServerHelper.ToNullableInt32(vCompId); 
                        departmentMaster.id = SqlServerHelper.ToNullableInt32(vid); 
                        departmentMaster.DepartmentName = SqlServerHelper.ToString(vDepartmentName); 

                    }
                    catch(Exception ex)
                    {
                        if(ex is System.NullReferenceException)
                        {
                            __rowsAffected = 0; 
                        }
                        else
                        {
                            throw ex; 
                        }
                    }
                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }
            
            return __rowsAffected; 
        }

        public int Update(DepartmentMaster departmentMaster)
        {
            int __rowsAffected = 0;
            
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("DepartmentMasterUpdate"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                // Add command parameters
                SqlParameter vDepId = new SqlParameter("@DepId", SqlDbType.Int);
                vDepId.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vDepId);
                SqlParameter vCompId = new SqlParameter("@CompId", SqlDbType.Int);
                vCompId.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vCompId);
                SqlParameter vid = new SqlParameter("@id", SqlDbType.Int);
                vid.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vid);
                SqlParameter vDepartmentName = new SqlParameter("@DepartmentName", SqlDbType.VarChar, 70);
                vDepartmentName.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vDepartmentName);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(vDepId, departmentMaster.DepId);
                SqlServerHelper.SetParameterValue(vCompId, departmentMaster.CompId);
                SqlServerHelper.SetParameterValue(vid, departmentMaster.id);
                SqlServerHelper.SetParameterValue(vDepartmentName, departmentMaster.DepartmentName);

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery(); 
                    if(__rowsAffected == 0)
                    {
                        return __rowsAffected; 
                    }
                    

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }
            
            return __rowsAffected; 
        }

        public int Delete(DepartmentMaster departmentMaster)
        {
            int __rowsAffected = 0;
            
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("DepartmentMasterDelete"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Add command parameters
                    SqlParameter vDepId = new SqlParameter("@DepId", SqlDbType.Int);
                    vDepId.Direction = ParameterDirection.Input; 
                    sqlCommand.Parameters.Add(vDepId);

                    // Set input parameter values
                    SqlServerHelper.SetParameterValue(vDepId, departmentMaster.DepId);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery(); 

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }
            
            return __rowsAffected; 
        }

        public int Insert(DepartmentMaster departmentMaster)
        {
            int __rowsAffected = 0;
            
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("DepartmentMasterInsert"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                // Add command parameters
                SqlParameter vDepId = new SqlParameter("@DepId", SqlDbType.Int);
                vDepId.Direction = ParameterDirection.InputOutput; 
                sqlCommand.Parameters.Add(vDepId);
                SqlParameter vCompId = new SqlParameter("@CompId", SqlDbType.Int);
                vCompId.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vCompId);
                SqlParameter vid = new SqlParameter("@id", SqlDbType.Int);
                vid.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vid);
                SqlParameter vDepartmentName = new SqlParameter("@DepartmentName", SqlDbType.VarChar, 70);
                vDepartmentName.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vDepartmentName);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(
                    vDepId, 
                    departmentMaster.DepId, 
                    0);
                SqlServerHelper.SetParameterValue(vCompId, departmentMaster.CompId);
                SqlServerHelper.SetParameterValue(vid, departmentMaster.id);
                SqlServerHelper.SetParameterValue(vDepartmentName, departmentMaster.DepartmentName);

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery(); 
                    if(__rowsAffected == 0)
                    {
                        return __rowsAffected; 
                    }
                    

                    // Get output parameter values
                    departmentMaster.DepId = SqlServerHelper.ToInt32(vDepId); 

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }
            
            return __rowsAffected; 
        }

        public IReader<DepartmentMaster> ListAll()
        {
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("DepartmentMasterListAll"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                // Execute command
                SqlDataReader reader = sqlCommand.ExecuteReader(AttachReaderCommand(sqlCommand));

                // Return reader
                return new SqlServerDepartmentMasterReader(reader); 
            }
        }

    }

    public partial class SqlServerDepartmentMasterReader : IReader<DepartmentMaster>
    {
        private SqlDataReader sqlDataReader;

        private DepartmentMaster _DepartmentMaster;

        private int _DepIdOrdinal = -1;
        private int _CompIdOrdinal = -1;
        private int _idOrdinal = -1;
        private int _DepartmentNameOrdinal = -1;

        public SqlServerDepartmentMasterReader(SqlDataReader sqlDataReader)
        {
            this.sqlDataReader = sqlDataReader; 
            for (int  i = 0; i < sqlDataReader.FieldCount; i++)
            {
                string columnName = sqlDataReader.GetName(i);
                columnName = columnName.ToUpper(); 
                switch (columnName)
                {
                    case "DEPID":
                        _DepIdOrdinal = i; 
                        break;
                    
                    case "COMPID":
                        _CompIdOrdinal = i; 
                        break;
                    
                    case "ID":
                        _idOrdinal = i; 
                        break;
                    
                    case "DEPARTMENTNAME":
                        _DepartmentNameOrdinal = i; 
                        break;
                    
                }
            }
        }

        #region IReader<DepartmentMaster> Implementation
        
        public bool Read()
        {
            _DepartmentMaster = null; 
            return this.sqlDataReader.Read(); 
        }

        public DepartmentMaster Current
        {
            get
            {
                if(_DepartmentMaster == null)
                {
                    _DepartmentMaster = new DepartmentMaster();
                    if(_DepIdOrdinal != -1)
                    {
                        _DepartmentMaster.DepId = SqlServerHelper.ToInt32(sqlDataReader, _DepIdOrdinal); 
                    }
                    _DepartmentMaster.CompId = SqlServerHelper.ToNullableInt32(sqlDataReader, _CompIdOrdinal); 
                    _DepartmentMaster.id = SqlServerHelper.ToNullableInt32(sqlDataReader, _idOrdinal); 
                    _DepartmentMaster.DepartmentName = SqlServerHelper.ToString(sqlDataReader, _DepartmentNameOrdinal); 
                }
                

                return _DepartmentMaster; 
            }
        }

        public void Close()
        {
            sqlDataReader.Close();
        }

        public List<DepartmentMaster> ToList()
        {
            List<DepartmentMaster> list = new List<DepartmentMaster>();
            while(this.Read())
            {
                list.Add(this.Current);
            }
            this.Close();
            return list; 
        }

        public DataTable ToDataTable()
        {
            DataTable dataTable = new DataTable();
            dataTable.Load(sqlDataReader);
            return dataTable; 
        }

        #endregion
        
        #region IDisposable Implementation
        
        public void Dispose()
        {
            sqlDataReader.Dispose();
        }
        #endregion
        
        #region IEnumerable<DepartmentMaster> Implementation
        
        public IEnumerator<DepartmentMaster> GetEnumerator()
        {
            return new DepartmentMasterEnumerator(this); 
        }

        #endregion
        
        #region IEnumerable Implementation
        
        IEnumerator IEnumerable.GetEnumerator()
        {
            return new DepartmentMasterEnumerator(this); 
        }

        #endregion
        
        
        private partial class DepartmentMasterEnumerator : IEnumerator<DepartmentMaster>
        {
            private IReader<DepartmentMaster> departmentMasterReader;

            public DepartmentMasterEnumerator(IReader<DepartmentMaster> departmentMasterReader)
            {
                this.departmentMasterReader = departmentMasterReader; 
            }

            #region IEnumerator<DepartmentMaster> Members
            
            public DepartmentMaster Current
            {
                get { return this.departmentMasterReader.Current; }
            }

            #endregion
            
            #region IDisposable Members
            
            public void Dispose()
            {
                this.departmentMasterReader.Dispose();
            }

            #endregion
            
            #region IEnumerator Members
            
            object IEnumerator.Current
            {
                get { return this.departmentMasterReader.Current; }
            }

            public bool MoveNext()
            {
                return this.departmentMasterReader.Read(); 
            }

            public void Reset()
            {
                throw new Exception("Reset of departmentmaster reader is not supported."); 
            }

            #endregion
            
        }
    }
}
