// This code was generated by an EVALUATION copy of Schematrix SchemaCoder.
// Redistribution of this source code, or an application developed from it, is forbidden.
// Modification of this source code to remove this comment is also forbidden.
// Please visit http://www.schematrix.com/ to obtain a license to use this software.


using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.IO;

namespace JTMSProject
{
    public partial class JobgroupMaster
    {
        private static IJobgroupMasterPersister _DefaultPersister;
        private IJobgroupMasterPersister _Persister;
        private int _JobGId;
        private int? _id;
        private int? _CompId;
        private string _JobGroupName;

        static JobgroupMaster()
        {
            // Assign default persister
            _DefaultPersister = new SqlServerJobgroupMasterPersister();
        }

        public JobgroupMaster()
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister; 
        }

        public JobgroupMaster(int _JobGId)
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister; 

            // Assign method parameter to private fields
            this._JobGId = _JobGId; 

            // Call associated retrieve method
            Retrieve();
        }

        public JobgroupMaster(DataRow row)
        {
            // Assign default persister to instance persister
            _Persister = _DefaultPersister; 

            // Assign column values to private members
            for (int  i = 0; i < row.Table.Columns.Count; i++)
            {
                switch (row.Table.Columns[i].ColumnName.ToUpper())
                {
                    case "JOBGID":
                        this.JobGId = Convert.ToInt32(row[i, DataRowVersion.Current]); 
                        break;
                    
                    case "ID":
                        if(row.IsNull(i) == false)
                        {
                            this.id = Convert.ToInt32(row[i, DataRowVersion.Current]); 
                        }
                        break;
                    
                    case "COMPID":
                        if(row.IsNull(i) == false)
                        {
                            this.CompId = Convert.ToInt32(row[i, DataRowVersion.Current]); 
                        }
                        break;
                    
                    case "JOBGROUPNAME":
                        if(row.IsNull(i) == false)
                        {
                            this.JobGroupName = (string)row[i, DataRowVersion.Current]; 
                        }
                        break;
                    
                }
            }
        }

        public static IJobgroupMasterPersister DefaultPersister
        {
            get { return _DefaultPersister; }
            set { _DefaultPersister = value; }
        }

        public IJobgroupMasterPersister Persister
        {
            get { return _Persister; }
            set { _Persister = value; }
        }

        public int JobGId
        {
            get { return _JobGId; }
            set { _JobGId = value; }
        }

        public int? id
        {
            get { return _id; }
            set { _id = value; }
        }

        public int? CompId
        {
            get { return _CompId; }
            set { _CompId = value; }
        }

        public string JobGroupName
        {
            get { return _JobGroupName; }
            set { _JobGroupName = value; }
        }

        public virtual void Clone(JobgroupMaster sourceObject)
        {
            // Clone attributes from source object
            this._JobGId = sourceObject.JobGId; 
            this._id = sourceObject.id; 
            this._CompId = sourceObject.CompId; 
            this._JobGroupName = sourceObject.JobGroupName; 
        }

        public virtual int Retrieve()
        {
            return _Persister.Retrieve(this); 
        }

        public virtual int Update()
        {
            return _Persister.Update(this); 
        }

        public virtual int Delete()
        {
            return _Persister.Delete(this); 
        }

        public virtual int Insert()
        {
            return _Persister.Insert(this); 
        }

        public static IReader<JobgroupMaster> ListAll()
        {
            return _DefaultPersister.ListAll(); 
        }

    }
    
    public partial interface IJobgroupMasterPersister
    {
        int Retrieve(JobgroupMaster jobgroupMaster);
        int Update(JobgroupMaster jobgroupMaster);
        int Delete(JobgroupMaster jobgroupMaster);
        int Insert(JobgroupMaster jobgroupMaster);
        IReader<JobgroupMaster> ListAll();
    }
    
    public partial class SqlServerJobgroupMasterPersister : SqlPersisterBase, IJobgroupMasterPersister
    {
        public SqlServerJobgroupMasterPersister()
        {
        }

        public SqlServerJobgroupMasterPersister(string connectionString) : base(connectionString)
        {
        }

        public SqlServerJobgroupMasterPersister(SqlConnection connection) : base(connection)
        {
        }

        public SqlServerJobgroupMasterPersister(SqlTransaction transaction) : base(transaction)
        {
        }

        public int Retrieve(JobgroupMaster jobgroupMaster)
        {
            int __rowsAffected = 1;
            
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("JobgroupMasterGet"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Add command parameters
                    SqlParameter vJobGId = new SqlParameter("@JobGId", SqlDbType.Int);
                    vJobGId.Direction = ParameterDirection.InputOutput; 
                    sqlCommand.Parameters.Add(vJobGId);
                    SqlParameter vid = new SqlParameter("@id", SqlDbType.Int);
                    vid.Direction = ParameterDirection.Output; 
                    sqlCommand.Parameters.Add(vid);
                    SqlParameter vCompId = new SqlParameter("@CompId", SqlDbType.Int);
                    vCompId.Direction = ParameterDirection.Output; 
                    sqlCommand.Parameters.Add(vCompId);
                    SqlParameter vJobGroupName = new SqlParameter("@JobGroupName", SqlDbType.VarChar, 70);
                    vJobGroupName.Direction = ParameterDirection.Output; 
                    sqlCommand.Parameters.Add(vJobGroupName);

                    // Set input parameter values
                    SqlServerHelper.SetParameterValue(vJobGId, jobgroupMaster.JobGId);

                    // Execute command
                    sqlCommand.ExecuteNonQuery();

                    try
                    {
                        // Get output parameter values
                        jobgroupMaster.JobGId = SqlServerHelper.ToInt32(vJobGId); 
                        jobgroupMaster.id = SqlServerHelper.ToNullableInt32(vid); 
                        jobgroupMaster.CompId = SqlServerHelper.ToNullableInt32(vCompId); 
                        jobgroupMaster.JobGroupName = SqlServerHelper.ToString(vJobGroupName); 

                    }
                    catch(Exception ex)
                    {
                        if(ex is System.NullReferenceException)
                        {
                            __rowsAffected = 0; 
                        }
                        else
                        {
                            throw ex; 
                        }
                    }
                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }
            
            return __rowsAffected; 
        }

        public int Update(JobgroupMaster jobgroupMaster)
        {
            int __rowsAffected = 0;
            
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("JobgroupMasterUpdate"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                // Add command parameters
                SqlParameter vJobGId = new SqlParameter("@JobGId", SqlDbType.Int);
                vJobGId.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vJobGId);
                SqlParameter vid = new SqlParameter("@id", SqlDbType.Int);
                vid.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vid);
                SqlParameter vCompId = new SqlParameter("@CompId", SqlDbType.Int);
                vCompId.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vCompId);
                SqlParameter vJobGroupName = new SqlParameter("@JobGroupName", SqlDbType.VarChar, 70);
                vJobGroupName.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vJobGroupName);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(vJobGId, jobgroupMaster.JobGId);
                SqlServerHelper.SetParameterValue(vid, jobgroupMaster.id);
                SqlServerHelper.SetParameterValue(vCompId, jobgroupMaster.CompId);
                SqlServerHelper.SetParameterValue(vJobGroupName, jobgroupMaster.JobGroupName);

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery(); 
                    if(__rowsAffected == 0)
                    {
                        return __rowsAffected; 
                    }
                    

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }
            
            return __rowsAffected; 
        }

        public int Delete(JobgroupMaster jobgroupMaster)
        {
            int __rowsAffected = 0;
            
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("JobgroupMasterDelete"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Add command parameters
                    SqlParameter vJobGId = new SqlParameter("@JobGId", SqlDbType.Int);
                    vJobGId.Direction = ParameterDirection.Input; 
                    sqlCommand.Parameters.Add(vJobGId);

                    // Set input parameter values
                    SqlServerHelper.SetParameterValue(vJobGId, jobgroupMaster.JobGId);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery(); 

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }
            
            return __rowsAffected; 
        }

        public int Insert(JobgroupMaster jobgroupMaster)
        {
            int __rowsAffected = 0;
            
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("JobgroupMasterInsert"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                // Add command parameters
                SqlParameter vJobGId = new SqlParameter("@JobGId", SqlDbType.Int);
                vJobGId.Direction = ParameterDirection.InputOutput; 
                sqlCommand.Parameters.Add(vJobGId);
                SqlParameter vid = new SqlParameter("@id", SqlDbType.Int);
                vid.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vid);
                SqlParameter vCompId = new SqlParameter("@CompId", SqlDbType.Int);
                vCompId.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vCompId);
                SqlParameter vJobGroupName = new SqlParameter("@JobGroupName", SqlDbType.VarChar, 70);
                vJobGroupName.Direction = ParameterDirection.Input; 
                sqlCommand.Parameters.Add(vJobGroupName);

                // Set input parameter values
                SqlServerHelper.SetParameterValue(
                    vJobGId, 
                    jobgroupMaster.JobGId, 
                    0);
                SqlServerHelper.SetParameterValue(vid, jobgroupMaster.id);
                SqlServerHelper.SetParameterValue(vCompId, jobgroupMaster.CompId);
                SqlServerHelper.SetParameterValue(vJobGroupName, jobgroupMaster.JobGroupName);

                try
                {
                    // Attach command
                    AttachCommand(sqlCommand);

                    // Execute command
                    __rowsAffected = sqlCommand.ExecuteNonQuery(); 
                    if(__rowsAffected == 0)
                    {
                        return __rowsAffected; 
                    }
                    

                    // Get output parameter values
                    jobgroupMaster.JobGId = SqlServerHelper.ToInt32(vJobGId); 

                }
                finally
                {
                    // Detach command
                    DetachCommand(sqlCommand);
                }

            }
            
            return __rowsAffected; 
        }

        public IReader<JobgroupMaster> ListAll()
        {
            // Create command
            using (SqlCommand sqlCommand = new SqlCommand("JobgroupMasterListAll"))
            {
                // Set command type
                sqlCommand.CommandType = CommandType.StoredProcedure; 

                // Execute command
                SqlDataReader reader = sqlCommand.ExecuteReader(AttachReaderCommand(sqlCommand));

                // Return reader
                return new SqlServerJobgroupMasterReader(reader); 
            }
        }

    }

    public partial class SqlServerJobgroupMasterReader : IReader<JobgroupMaster>
    {
        private SqlDataReader sqlDataReader;

        private JobgroupMaster _JobgroupMaster;

        private int _JobGIdOrdinal = -1;
        private int _idOrdinal = -1;
        private int _CompIdOrdinal = -1;
        private int _JobGroupNameOrdinal = -1;

        public SqlServerJobgroupMasterReader(SqlDataReader sqlDataReader)
        {
            this.sqlDataReader = sqlDataReader; 
            for (int  i = 0; i < sqlDataReader.FieldCount; i++)
            {
                string columnName = sqlDataReader.GetName(i);
                columnName = columnName.ToUpper(); 
                switch (columnName)
                {
                    case "JOBGID":
                        _JobGIdOrdinal = i; 
                        break;
                    
                    case "ID":
                        _idOrdinal = i; 
                        break;
                    
                    case "COMPID":
                        _CompIdOrdinal = i; 
                        break;
                    
                    case "JOBGROUPNAME":
                        _JobGroupNameOrdinal = i; 
                        break;
                    
                }
            }
        }

        #region IReader<JobgroupMaster> Implementation
        
        public bool Read()
        {
            _JobgroupMaster = null; 
            return this.sqlDataReader.Read(); 
        }

        public JobgroupMaster Current
        {
            get
            {
                if(_JobgroupMaster == null)
                {
                    _JobgroupMaster = new JobgroupMaster();
                    if(_JobGIdOrdinal != -1)
                    {
                        _JobgroupMaster.JobGId = SqlServerHelper.ToInt32(sqlDataReader, _JobGIdOrdinal); 
                    }
                    _JobgroupMaster.id = SqlServerHelper.ToNullableInt32(sqlDataReader, _idOrdinal); 
                    _JobgroupMaster.CompId = SqlServerHelper.ToNullableInt32(sqlDataReader, _CompIdOrdinal); 
                    _JobgroupMaster.JobGroupName = SqlServerHelper.ToString(sqlDataReader, _JobGroupNameOrdinal); 
                }
                

                return _JobgroupMaster; 
            }
        }

        public void Close()
        {
            sqlDataReader.Close();
        }

        public List<JobgroupMaster> ToList()
        {
            List<JobgroupMaster> list = new List<JobgroupMaster>();
            while(this.Read())
            {
                list.Add(this.Current);
            }
            this.Close();
            return list; 
        }

        public DataTable ToDataTable()
        {
            DataTable dataTable = new DataTable();
            dataTable.Load(sqlDataReader);
            return dataTable; 
        }

        #endregion
        
        #region IDisposable Implementation
        
        public void Dispose()
        {
            sqlDataReader.Dispose();
        }
        #endregion
        
        #region IEnumerable<JobgroupMaster> Implementation
        
        public IEnumerator<JobgroupMaster> GetEnumerator()
        {
            return new JobgroupMasterEnumerator(this); 
        }

        #endregion
        
        #region IEnumerable Implementation
        
        IEnumerator IEnumerable.GetEnumerator()
        {
            return new JobgroupMasterEnumerator(this); 
        }

        #endregion
        
        
        private partial class JobgroupMasterEnumerator : IEnumerator<JobgroupMaster>
        {
            private IReader<JobgroupMaster> jobgroupMasterReader;

            public JobgroupMasterEnumerator(IReader<JobgroupMaster> jobgroupMasterReader)
            {
                this.jobgroupMasterReader = jobgroupMasterReader; 
            }

            #region IEnumerator<JobgroupMaster> Members
            
            public JobgroupMaster Current
            {
                get { return this.jobgroupMasterReader.Current; }
            }

            #endregion
            
            #region IDisposable Members
            
            public void Dispose()
            {
                this.jobgroupMasterReader.Dispose();
            }

            #endregion
            
            #region IEnumerator Members
            
            object IEnumerator.Current
            {
                get { return this.jobgroupMasterReader.Current; }
            }

            public bool MoveNext()
            {
                return this.jobgroupMasterReader.Read(); 
            }

            public void Reset()
            {
                throw new Exception("Reset of jobgroupmaster reader is not supported."); 
            }

            #endregion
            
        }
    }
}
